
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=pperzyna/pact-example

before_script:
  - docker pull "${IMAGE_NAME}:provider" || true
  - docker pull "${IMAGE_NAME}:consumer" || true  

script:
  - cd consumer; docker build --cache-from "${IMAGE_NAME}" --tag "${IMAGE_NAME}:consumer-${TRAVIS_COMMIT}" -f Dockerfile src/
  - cd ../provider; docker build --cache-from "${IMAGE_NAME}" --tag "${IMAGE_NAME}:provider-${TRAVIS_COMMIT}" -f Dockerfile ./src/

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  - provider: script
    script: 
      - docker tag "${IMAGE_NAME}:consumer-${TRAVIS_COMMIT}" "${IMAGE_NAME}:consumer" && docker push "${IMAGE_NAME}:consumer" 
      - docker tag "${IMAGE_NAME}:provider-${TRAVIS_COMMIT}" "${IMAGE_NAME}:provider" && docker push "${IMAGE_NAME}:provider" 
    on:
      branch: master
  - provider: script
    script: 
      - docker tag "${IMAGE_NAME}:consumer-${TRAVIS_COMMIT}" "${IMAGE_NAME}:consumer-${TRAVIS_TAG}" && docker push "${IMAGE_NAME}:consumer-${TRAVIS_TAG}" 
      - docker tag "${IMAGE_NAME}:provider-${TRAVIS_COMMIT}" "${IMAGE_NAME}:provider-${TRAVIS_TAG}" && docker push "${IMAGE_NAME}:provider-${TRAVIS_TAG}" 
    on:
      tags: true